// Generated by gencpp from file xf_mic_api/Adjust_Voice_srv.msg
// DO NOT EDIT!


#ifndef XF_MIC_API_MESSAGE_ADJUST_VOICE_SRV_H
#define XF_MIC_API_MESSAGE_ADJUST_VOICE_SRV_H

#include <ros/service_traits.h>


#include <xf_mic_api/Adjust_Voice_srvRequest.h>
#include <xf_mic_api/Adjust_Voice_srvResponse.h>


namespace xf_mic_api
{

struct Adjust_Voice_srv
{

typedef Adjust_Voice_srvRequest Request;
typedef Adjust_Voice_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Adjust_Voice_srv
} // namespace xf_mic_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xf_mic_api::Adjust_Voice_srv > {
  static const char* value()
  {
    return "1fe39a8a9d88b2ef00e2ad1af9f88f0d";
  }

  static const char* value(const ::xf_mic_api::Adjust_Voice_srv&) { return value(); }
};

template<>
struct DataType< ::xf_mic_api::Adjust_Voice_srv > {
  static const char* value()
  {
    return "xf_mic_api/Adjust_Voice_srv";
  }

  static const char* value(const ::xf_mic_api::Adjust_Voice_srv&) { return value(); }
};


// service_traits::MD5Sum< ::xf_mic_api::Adjust_Voice_srvRequest> should match
// service_traits::MD5Sum< ::xf_mic_api::Adjust_Voice_srv >
template<>
struct MD5Sum< ::xf_mic_api::Adjust_Voice_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_api::Adjust_Voice_srv >::value();
  }
  static const char* value(const ::xf_mic_api::Adjust_Voice_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_api::Adjust_Voice_srvRequest> should match
// service_traits::DataType< ::xf_mic_api::Adjust_Voice_srv >
template<>
struct DataType< ::xf_mic_api::Adjust_Voice_srvRequest>
{
  static const char* value()
  {
    return DataType< ::xf_mic_api::Adjust_Voice_srv >::value();
  }
  static const char* value(const ::xf_mic_api::Adjust_Voice_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xf_mic_api::Adjust_Voice_srvResponse> should match
// service_traits::MD5Sum< ::xf_mic_api::Adjust_Voice_srv >
template<>
struct MD5Sum< ::xf_mic_api::Adjust_Voice_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_api::Adjust_Voice_srv >::value();
  }
  static const char* value(const ::xf_mic_api::Adjust_Voice_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_api::Adjust_Voice_srvResponse> should match
// service_traits::DataType< ::xf_mic_api::Adjust_Voice_srv >
template<>
struct DataType< ::xf_mic_api::Adjust_Voice_srvResponse>
{
  static const char* value()
  {
    return DataType< ::xf_mic_api::Adjust_Voice_srv >::value();
  }
  static const char* value(const ::xf_mic_api::Adjust_Voice_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XF_MIC_API_MESSAGE_ADJUST_VOICE_SRV_H
