// Generated by gencpp from file xf_mic_api/Adjust_Voice_srvRequest.msg
// DO NOT EDIT!


#ifndef XF_MIC_API_MESSAGE_ADJUST_VOICE_SRVREQUEST_H
#define XF_MIC_API_MESSAGE_ADJUST_VOICE_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xf_mic_api
{
template <class ContainerAllocator>
struct Adjust_Voice_srvRequest_
{
  typedef Adjust_Voice_srvRequest_<ContainerAllocator> Type;

  Adjust_Voice_srvRequest_()
    : voice(0)  {
    }
  Adjust_Voice_srvRequest_(const ContainerAllocator& _alloc)
    : voice(0)  {
  (void)_alloc;
    }



   typedef int8_t _voice_type;
  _voice_type voice;





  typedef boost::shared_ptr< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Adjust_Voice_srvRequest_

typedef ::xf_mic_api::Adjust_Voice_srvRequest_<std::allocator<void> > Adjust_Voice_srvRequest;

typedef boost::shared_ptr< ::xf_mic_api::Adjust_Voice_srvRequest > Adjust_Voice_srvRequestPtr;
typedef boost::shared_ptr< ::xf_mic_api::Adjust_Voice_srvRequest const> Adjust_Voice_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator1> & lhs, const ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.voice == rhs.voice;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator1> & lhs, const ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xf_mic_api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2f39246393da29cc024092b47f7dce4";
  }

  static const char* value(const ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2f39246393da29cULL;
  static const uint64_t static_value2 = 0xc024092b47f7dce4ULL;
};

template<class ContainerAllocator>
struct DataType< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xf_mic_api/Adjust_Voice_srvRequest";
  }

  static const char* value(const ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 voice # 1-100\n"
;
  }

  static const char* value(const ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voice);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Adjust_Voice_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xf_mic_api::Adjust_Voice_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "voice: ";
    Printer<int8_t>::stream(s, indent + "  ", v.voice);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XF_MIC_API_MESSAGE_ADJUST_VOICE_SRVREQUEST_H
