// Generated by gencpp from file xf_mic_api/Delete_Target_Wav_srvRequest.msg
// DO NOT EDIT!


#ifndef XF_MIC_API_MESSAGE_DELETE_TARGET_WAV_SRVREQUEST_H
#define XF_MIC_API_MESSAGE_DELETE_TARGET_WAV_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xf_mic_api
{
template <class ContainerAllocator>
struct Delete_Target_Wav_srvRequest_
{
  typedef Delete_Target_Wav_srvRequest_<ContainerAllocator> Type;

  Delete_Target_Wav_srvRequest_()
    : filename()  {
    }
  Delete_Target_Wav_srvRequest_(const ContainerAllocator& _alloc)
    : filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _filename_type;
  _filename_type filename;





  typedef boost::shared_ptr< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Delete_Target_Wav_srvRequest_

typedef ::xf_mic_api::Delete_Target_Wav_srvRequest_<std::allocator<void> > Delete_Target_Wav_srvRequest;

typedef boost::shared_ptr< ::xf_mic_api::Delete_Target_Wav_srvRequest > Delete_Target_Wav_srvRequestPtr;
typedef boost::shared_ptr< ::xf_mic_api::Delete_Target_Wav_srvRequest const> Delete_Target_Wav_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator1> & lhs, const ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.filename == rhs.filename;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator1> & lhs, const ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xf_mic_api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x030824f52a0628eaULL;
  static const uint64_t static_value2 = 0xd956fb9d67e66ae9ULL;
};

template<class ContainerAllocator>
struct DataType< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xf_mic_api/Delete_Target_Wav_srvRequest";
  }

  static const char* value(const ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string filename\n"
;
  }

  static const char* value(const ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Delete_Target_Wav_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xf_mic_api::Delete_Target_Wav_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XF_MIC_API_MESSAGE_DELETE_TARGET_WAV_SRVREQUEST_H
