// Generated by gencpp from file xf_mic_api/Pcm_msg.msg
// DO NOT EDIT!


#ifndef XF_MIC_API_MESSAGE_PCM_MSG_H
#define XF_MIC_API_MESSAGE_PCM_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xf_mic_api
{
template <class ContainerAllocator>
struct Pcm_msg_
{
  typedef Pcm_msg_<ContainerAllocator> Type;

  Pcm_msg_()
    : length(0)
    , pcm_buf()  {
    }
  Pcm_msg_(const ContainerAllocator& _alloc)
    : length(0)
    , pcm_buf(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _length_type;
  _length_type length;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _pcm_buf_type;
  _pcm_buf_type pcm_buf;





  typedef boost::shared_ptr< ::xf_mic_api::Pcm_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xf_mic_api::Pcm_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Pcm_msg_

typedef ::xf_mic_api::Pcm_msg_<std::allocator<void> > Pcm_msg;

typedef boost::shared_ptr< ::xf_mic_api::Pcm_msg > Pcm_msgPtr;
typedef boost::shared_ptr< ::xf_mic_api::Pcm_msg const> Pcm_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xf_mic_api::Pcm_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xf_mic_api::Pcm_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xf_mic_api::Pcm_msg_<ContainerAllocator1> & lhs, const ::xf_mic_api::Pcm_msg_<ContainerAllocator2> & rhs)
{
  return lhs.length == rhs.length &&
    lhs.pcm_buf == rhs.pcm_buf;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xf_mic_api::Pcm_msg_<ContainerAllocator1> & lhs, const ::xf_mic_api::Pcm_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xf_mic_api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_api::Pcm_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_api::Pcm_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_api::Pcm_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_api::Pcm_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_api::Pcm_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_api::Pcm_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xf_mic_api::Pcm_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16b54b71ac26cea4c3b47ae21456fcc5";
  }

  static const char* value(const ::xf_mic_api::Pcm_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16b54b71ac26cea4ULL;
  static const uint64_t static_value2 = 0xc3b47ae21456fcc5ULL;
};

template<class ContainerAllocator>
struct DataType< ::xf_mic_api::Pcm_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xf_mic_api/Pcm_msg";
  }

  static const char* value(const ::xf_mic_api::Pcm_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xf_mic_api::Pcm_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 length\n"
"char[] pcm_buf\n"
;
  }

  static const char* value(const ::xf_mic_api::Pcm_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xf_mic_api::Pcm_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.length);
      stream.next(m.pcm_buf);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pcm_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xf_mic_api::Pcm_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xf_mic_api::Pcm_msg_<ContainerAllocator>& v)
  {
    s << indent << "length: ";
    Printer<int8_t>::stream(s, indent + "  ", v.length);
    s << indent << "pcm_buf[]" << std::endl;
    for (size_t i = 0; i < v.pcm_buf.size(); ++i)
    {
      s << indent << "  pcm_buf[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.pcm_buf[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XF_MIC_API_MESSAGE_PCM_MSG_H
