// Generated by gencpp from file xf_mic_api/Stop_To_Play_srv.msg
// DO NOT EDIT!


#ifndef XF_MIC_API_MESSAGE_STOP_TO_PLAY_SRV_H
#define XF_MIC_API_MESSAGE_STOP_TO_PLAY_SRV_H

#include <ros/service_traits.h>


#include <xf_mic_api/Stop_To_Play_srvRequest.h>
#include <xf_mic_api/Stop_To_Play_srvResponse.h>


namespace xf_mic_api
{

struct Stop_To_Play_srv
{

typedef Stop_To_Play_srvRequest Request;
typedef Stop_To_Play_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stop_To_Play_srv
} // namespace xf_mic_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xf_mic_api::Stop_To_Play_srv > {
  static const char* value()
  {
    return "0204824c56e88dfd8a1e8d415331b53f";
  }

  static const char* value(const ::xf_mic_api::Stop_To_Play_srv&) { return value(); }
};

template<>
struct DataType< ::xf_mic_api::Stop_To_Play_srv > {
  static const char* value()
  {
    return "xf_mic_api/Stop_To_Play_srv";
  }

  static const char* value(const ::xf_mic_api::Stop_To_Play_srv&) { return value(); }
};


// service_traits::MD5Sum< ::xf_mic_api::Stop_To_Play_srvRequest> should match
// service_traits::MD5Sum< ::xf_mic_api::Stop_To_Play_srv >
template<>
struct MD5Sum< ::xf_mic_api::Stop_To_Play_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_api::Stop_To_Play_srv >::value();
  }
  static const char* value(const ::xf_mic_api::Stop_To_Play_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_api::Stop_To_Play_srvRequest> should match
// service_traits::DataType< ::xf_mic_api::Stop_To_Play_srv >
template<>
struct DataType< ::xf_mic_api::Stop_To_Play_srvRequest>
{
  static const char* value()
  {
    return DataType< ::xf_mic_api::Stop_To_Play_srv >::value();
  }
  static const char* value(const ::xf_mic_api::Stop_To_Play_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xf_mic_api::Stop_To_Play_srvResponse> should match
// service_traits::MD5Sum< ::xf_mic_api::Stop_To_Play_srv >
template<>
struct MD5Sum< ::xf_mic_api::Stop_To_Play_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_api::Stop_To_Play_srv >::value();
  }
  static const char* value(const ::xf_mic_api::Stop_To_Play_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_api::Stop_To_Play_srvResponse> should match
// service_traits::DataType< ::xf_mic_api::Stop_To_Play_srv >
template<>
struct DataType< ::xf_mic_api::Stop_To_Play_srvResponse>
{
  static const char* value()
  {
    return DataType< ::xf_mic_api::Stop_To_Play_srv >::value();
  }
  static const char* value(const ::xf_mic_api::Stop_To_Play_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XF_MIC_API_MESSAGE_STOP_TO_PLAY_SRV_H
