// Generated by gencpp from file xf_mic_api/Stop_To_Play_srvRequest.msg
// DO NOT EDIT!


#ifndef XF_MIC_API_MESSAGE_STOP_TO_PLAY_SRVREQUEST_H
#define XF_MIC_API_MESSAGE_STOP_TO_PLAY_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xf_mic_api
{
template <class ContainerAllocator>
struct Stop_To_Play_srvRequest_
{
  typedef Stop_To_Play_srvRequest_<ContainerAllocator> Type;

  Stop_To_Play_srvRequest_()
    : stop_play(0)  {
    }
  Stop_To_Play_srvRequest_(const ContainerAllocator& _alloc)
    : stop_play(0)  {
  (void)_alloc;
    }



   typedef int8_t _stop_play_type;
  _stop_play_type stop_play;





  typedef boost::shared_ptr< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Stop_To_Play_srvRequest_

typedef ::xf_mic_api::Stop_To_Play_srvRequest_<std::allocator<void> > Stop_To_Play_srvRequest;

typedef boost::shared_ptr< ::xf_mic_api::Stop_To_Play_srvRequest > Stop_To_Play_srvRequestPtr;
typedef boost::shared_ptr< ::xf_mic_api::Stop_To_Play_srvRequest const> Stop_To_Play_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator1> & lhs, const ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.stop_play == rhs.stop_play;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator1> & lhs, const ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xf_mic_api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0aeb9c588e4cbf2a5e32b5d9a2d5b7d6";
  }

  static const char* value(const ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0aeb9c588e4cbf2aULL;
  static const uint64_t static_value2 = 0x5e32b5d9a2d5b7d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xf_mic_api/Stop_To_Play_srvRequest";
  }

  static const char* value(const ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 stop_play\n"
;
  }

  static const char* value(const ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stop_play);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Stop_To_Play_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xf_mic_api::Stop_To_Play_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "stop_play: ";
    Printer<int8_t>::stream(s, indent + "  ", v.stop_play);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XF_MIC_API_MESSAGE_STOP_TO_PLAY_SRVREQUEST_H
