// Generated by gencpp from file xf_mic_tts_online/Play_TTS_Online_srv.msg
// DO NOT EDIT!


#ifndef XF_MIC_TTS_ONLINE_MESSAGE_PLAY_TTS_ONLINE_SRV_H
#define XF_MIC_TTS_ONLINE_MESSAGE_PLAY_TTS_ONLINE_SRV_H

#include <ros/service_traits.h>


#include <xf_mic_tts_online/Play_TTS_Online_srvRequest.h>
#include <xf_mic_tts_online/Play_TTS_Online_srvResponse.h>


namespace xf_mic_tts_online
{

struct Play_TTS_Online_srv
{

typedef Play_TTS_Online_srvRequest Request;
typedef Play_TTS_Online_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Play_TTS_Online_srv
} // namespace xf_mic_tts_online


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xf_mic_tts_online::Play_TTS_Online_srv > {
  static const char* value()
  {
    return "8933c186a674fd503166dc2df31b3720";
  }

  static const char* value(const ::xf_mic_tts_online::Play_TTS_Online_srv&) { return value(); }
};

template<>
struct DataType< ::xf_mic_tts_online::Play_TTS_Online_srv > {
  static const char* value()
  {
    return "xf_mic_tts_online/Play_TTS_Online_srv";
  }

  static const char* value(const ::xf_mic_tts_online::Play_TTS_Online_srv&) { return value(); }
};


// service_traits::MD5Sum< ::xf_mic_tts_online::Play_TTS_Online_srvRequest> should match
// service_traits::MD5Sum< ::xf_mic_tts_online::Play_TTS_Online_srv >
template<>
struct MD5Sum< ::xf_mic_tts_online::Play_TTS_Online_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_tts_online::Play_TTS_Online_srv >::value();
  }
  static const char* value(const ::xf_mic_tts_online::Play_TTS_Online_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_tts_online::Play_TTS_Online_srvRequest> should match
// service_traits::DataType< ::xf_mic_tts_online::Play_TTS_Online_srv >
template<>
struct DataType< ::xf_mic_tts_online::Play_TTS_Online_srvRequest>
{
  static const char* value()
  {
    return DataType< ::xf_mic_tts_online::Play_TTS_Online_srv >::value();
  }
  static const char* value(const ::xf_mic_tts_online::Play_TTS_Online_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xf_mic_tts_online::Play_TTS_Online_srvResponse> should match
// service_traits::MD5Sum< ::xf_mic_tts_online::Play_TTS_Online_srv >
template<>
struct MD5Sum< ::xf_mic_tts_online::Play_TTS_Online_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_tts_online::Play_TTS_Online_srv >::value();
  }
  static const char* value(const ::xf_mic_tts_online::Play_TTS_Online_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_tts_online::Play_TTS_Online_srvResponse> should match
// service_traits::DataType< ::xf_mic_tts_online::Play_TTS_Online_srv >
template<>
struct DataType< ::xf_mic_tts_online::Play_TTS_Online_srvResponse>
{
  static const char* value()
  {
    return DataType< ::xf_mic_tts_online::Play_TTS_Online_srv >::value();
  }
  static const char* value(const ::xf_mic_tts_online::Play_TTS_Online_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XF_MIC_TTS_ONLINE_MESSAGE_PLAY_TTS_ONLINE_SRV_H
