// Generated by gencpp from file xf_mic_tts_online/Play_TTS_Online_srvRequest.msg
// DO NOT EDIT!


#ifndef XF_MIC_TTS_ONLINE_MESSAGE_PLAY_TTS_ONLINE_SRVREQUEST_H
#define XF_MIC_TTS_ONLINE_MESSAGE_PLAY_TTS_ONLINE_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xf_mic_tts_online
{
template <class ContainerAllocator>
struct Play_TTS_Online_srvRequest_
{
  typedef Play_TTS_Online_srvRequest_<ContainerAllocator> Type;

  Play_TTS_Online_srvRequest_()
    : text()
    , appID()
    , speakerName()  {
    }
  Play_TTS_Online_srvRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)
    , appID(_alloc)
    , speakerName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _appID_type;
  _appID_type appID;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _speakerName_type;
  _speakerName_type speakerName;





  typedef boost::shared_ptr< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Play_TTS_Online_srvRequest_

typedef ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<std::allocator<void> > Play_TTS_Online_srvRequest;

typedef boost::shared_ptr< ::xf_mic_tts_online::Play_TTS_Online_srvRequest > Play_TTS_Online_srvRequestPtr;
typedef boost::shared_ptr< ::xf_mic_tts_online::Play_TTS_Online_srvRequest const> Play_TTS_Online_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator1> & lhs, const ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text &&
    lhs.appID == rhs.appID &&
    lhs.speakerName == rhs.speakerName;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator1> & lhs, const ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xf_mic_tts_online

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa0b209b416110e6d0024ce69404cbd2";
  }

  static const char* value(const ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa0b209b416110e6ULL;
  static const uint64_t static_value2 = 0xd0024ce69404cbd2ULL;
};

template<class ContainerAllocator>
struct DataType< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xf_mic_tts_online/Play_TTS_Online_srvRequest";
  }

  static const char* value(const ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
"string appID\n"
"string speakerName\n"
;
  }

  static const char* value(const ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
      stream.next(m.appID);
      stream.next(m.speakerName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Play_TTS_Online_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xf_mic_tts_online::Play_TTS_Online_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
    s << indent << "appID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.appID);
    s << indent << "speakerName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.speakerName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XF_MIC_TTS_ONLINE_MESSAGE_PLAY_TTS_ONLINE_SRVREQUEST_H
